/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
namespace Demo
{
    public partial class Solution
    {
        public char FindTheDifference(string s, string t)
        {
            char res = (char)0;
            foreach (char c in s) res ^= c;
            foreach (char c in t) res ^= c;
            return res;
        }

        public char FindTheDifference2(string s, string t)
        {
            int[] m = new int[26];
            foreach (char c in s) ++m[c - 'a'];
            foreach (char c in t)
            {
                if (--m[c - 'a'] < 0) return c;
            }
            return '?';
        }
    }
}
